name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'postgres username'
        required: true
        type: string
      password:
        description: 'postres password'
        required: true
        type: string
      ip_addr:
        description: 'DB ip'
        required: true
        type: string
      tunnel:
        description: 'enable tunnel'
        type: choice
        required: true
        options:
        - true
        - false

jobs:
  No_tunnel:
    runs-on: ubuntu-latest
    if: "!${{ inputs.tunnel}}"
    steps:
    - name: test
      run: >
        echo python3
        ${{ inputs.username }}
        ${{ inputs.password }}
        ${{ inputs.id_addr }}   
  tunnel:
    runs-on: ubuntu-latest
    if: ${{ inputs.tunnel }}
    steps:
    - name: test
      run: >
        echo python3
        ${{ inputs.username }}
        ${{ inputs.password }}
        ${{ inputs.id_addr }}
        ${{ inputs.tunnel }}
