name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'postgres username'
        required: true
        type: string
      password:
        description: 'postres password'
        required: true
        type: string
      ip_addr:
        description: 'DB ip'
        required: true
        type: string
      tunnel:
        description: 'enable tunnel'
        type: choice
        options:
          - "enable"
          - "disable"
      destination:
        description: 'Eamil destination'
        required: true
        type: string
        default: '2f833729.hpe.onmicrosoft.com@amer.teams.ms'

jobs:
  No_tunnel:
    runs-on: ubuntu-latest
    if: "contains(inputs.tunnel, 'disable')" 
    steps: 
    - name: test
      run: >
        echo python3
        ${{ inputs.username }}
        ${{ inputs.password }}
        ${{ inputs.id_addr }}   
        ${{ inputs.destination }}
  tunnel:
    runs-on: ubuntu-latest
    if: "contains(inputs.tunnel, 'enable')" 
    steps:
    - name: test
      run: >
        echo python3
        ${{ inputs.username }}
        ${{ inputs.password }}
        ${{ inputs.id_addr }}
        ${{ inputs.tunnel }}
        ${{ inputs.destination }}
    
